version: "3.7"

services:
  app:
    build:
      context: ./
    env_file: ./.env
    ports:
      - 5000:5000

  localstack:
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    environment:
      - services=s3
      - DEBUG=1
